"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-25 19:55:50.262161
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from app.config import get_settings

# Embedding dimension is fixed at migration time. Changing EMBEDDING_DIMENSIONS later requires a
# re-embedding migration (see docs/adr/0005-providers-and-fakes.md).
DIM = get_settings().embedding_dimensions

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "result_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'dead')", name=op.f("ck_jobs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index(
        "ix_jobs_ready",
        "jobs",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued','failed')"),
    )
    op.create_index(
        "ix_jobs_running_lease",
        "jobs",
        ["locked_until"],
        unique=False,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("prefix", sa.String(length=32), nullable=False),
        sa.Column("key_hash", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("workspace_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("role IN ('admin', 'maintainer', 'agent', 'viewer')", name=op.f("ck_api_keys_role")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_api_keys_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("prefix", name=op.f("uq_api_keys_prefix")),
    )
    op.create_index(op.f("ix_api_keys_organization_id"), "api_keys", ["organization_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column(
            "before_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "after_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_logs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_org_created", "audit_logs", ["organization_id", "created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False)
    op.create_index("ix_audit_logs_resource", "audit_logs", ["resource_type", "resource_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_workspace_id"), "audit_logs", ["workspace_id"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=300), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_idempotency_keys_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_idempotency_keys")),
        sa.UniqueConstraint("organization_id", "key", name=op.f("uq_idempotency_keys_organization_id")),
    )
    op.create_index(op.f("ix_idempotency_keys_organization_id"), "idempotency_keys", ["organization_id"], unique=False)
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "settings_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_workspaces_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("organization_id", "name", name=op.f("uq_workspaces_organization_id")),
    )
    op.create_index(op.f("ix_workspaces_organization_id"), "workspaces", ["organization_id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_agents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_agents_workspace_id")),
    )
    op.create_index(op.f("ix_agents_organization_id"), "agents", ["organization_id"], unique=False)
    op.create_index(op.f("ix_agents_workspace_id"), "agents", ["workspace_id"], unique=False)
    op.create_table(
        "dream_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("window_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "input_window_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "checkpoint_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("requested_by_id", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "mode IN ('reflection', 'deduplication', 'pattern', 'contradiction', 'generalization', 'compression')",
            name=op.f("ck_dream_jobs_mode"),
        ),
        sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name=op.f("ck_dream_jobs_status")),
        sa.CheckConstraint(
            "trigger_type IN ('manual','schedule','event_count','memory_growth')",
            name=op.f("ck_dream_jobs_trigger"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_dream_jobs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_dream_jobs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dream_jobs")),
    )
    op.create_index(op.f("ix_dream_jobs_organization_id"), "dream_jobs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_dream_jobs_workspace_id"), "dream_jobs", ["workspace_id"], unique=False)
    op.create_index(
        "uq_dream_jobs_window",
        "dream_jobs",
        ["workspace_id", "mode", "window_hash"],
        unique=True,
        postgresql_where=sa.text("window_hash IS NOT NULL"),
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.String(length=200), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("embedding", Vector(DIM), nullable=True),
        sa.Column("experience_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_episodes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_episodes_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
        sa.UniqueConstraint(
            "workspace_id",
            "session_id",
            "task_id",
            name=op.f("uq_episodes_workspace_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_episodes_organization_id"), "episodes", ["organization_id"], unique=False)
    op.create_index(op.f("ix_episodes_workspace_id"), "episodes", ["workspace_id"], unique=False)
    op.create_table(
        "eval_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "summary_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "result_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_eval_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_eval_runs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_index(op.f("ix_eval_runs_organization_id"), "eval_runs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_eval_runs_workspace_id"), "eval_runs", ["workspace_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.String(length=200), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column(
            "payload_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "type IN ('user', 'assistant', 'tool', 'error', 'feedback', 'task', 'system')",
            name=op.f("ck_events_type"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(op.f("ix_events_organization_id"), "events", ["organization_id"], unique=False)
    op.create_index(op.f("ix_events_session_id"), "events", ["session_id"], unique=False)
    op.create_index(op.f("ix_events_workspace_id"), "events", ["workspace_id"], unique=False)
    op.create_index("ix_events_ws_occurred", "events", ["workspace_id", "occurred_at"], unique=False)
    op.create_table(
        "memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("layer", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("scope_type", sa.String(length=20), nullable=False),
        sa.Column("scope_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("review_state", sa.String(length=20), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("trust_score", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("utility_score", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(DIM), nullable=True),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || content)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("retrieval_count", sa.Integer(), nullable=False),
        sa.Column("last_retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_type", sa.String(length=30), nullable=False),
        sa.Column("created_by_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "review_state IN ('none', 'pending', 'approved', 'rejected')",
            name=op.f("ck_memories_review_state"),
        ),
        sa.CheckConstraint(
            "scope_type IN ('organization', 'workspace', 'project', 'agent', 'session')",
            name=op.f("ck_memories_scope_type"),
        ),
        sa.CheckConstraint(
            "status IN ('candidate', 'validated', 'active', 'disputed', 'superseded', 'archived', 'rejected')",
            name=op.f("ck_memories_status"),
        ),
        sa.CheckConstraint(
            "type IN ('fact', 'preference', 'procedure', 'rule', 'constraint', 'decision', 'lesson', 'pattern', 'warning', 'failure', 'success', 'relationship', 'context')",
            name=op.f("ck_memories_type"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1 AND trust_score BETWEEN 0 AND 1 AND importance BETWEEN 0 AND 1 AND utility_score BETWEEN 0 AND 1",
            name=op.f("ck_memories_scores"),
        ),
        sa.CheckConstraint("layer IN (3, 4)", name=op.f("ck_memories_layer")),
        sa.CheckConstraint("version >= 1", name=op.f("ck_memories_version")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memories_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_memories_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memories")),
    )
    op.create_index(
        "ix_memories_active_scope",
        "memories",
        ["organization_id", "workspace_id", "scope_type", "scope_id"],
        unique=False,
        postgresql_where=sa.text("status IN ('active','validated')"),
    )
    op.create_index("ix_memories_content_hash", "memories", ["workspace_id", "content_hash"], unique=False)
    op.create_index(op.f("ix_memories_organization_id"), "memories", ["organization_id"], unique=False)
    op.create_index("ix_memories_search_tsv", "memories", ["search_tsv"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_memories_workspace_id"), "memories", ["workspace_id"], unique=False)
    op.create_index("ix_memories_ws_status", "memories", ["workspace_id", "status"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_projects_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("workspace_id", "name", name=op.f("uq_projects_workspace_id")),
    )
    op.create_index(op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False)
    op.create_index(op.f("ix_projects_workspace_id"), "projects", ["workspace_id"], unique=False)
    op.create_table(
        "retrieval_traces",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "request_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "candidates_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "selected_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("context_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_retrieval_traces_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_retrieval_traces_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_traces")),
    )
    op.create_index(op.f("ix_retrieval_traces_organization_id"), "retrieval_traces", ["organization_id"], unique=False)
    op.create_index(op.f("ix_retrieval_traces_workspace_id"), "retrieval_traces", ["workspace_id"], unique=False)
    op.create_index("ix_retrieval_traces_ws_created", "retrieval_traces", ["workspace_id", "created_at"], unique=False)
    op.create_table(
        "scheduler_state",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("task", sa.String(length=50), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "counters_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_scheduler_state_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_scheduler_state_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduler_state")),
        sa.UniqueConstraint("workspace_id", "task", name=op.f("uq_scheduler_state_workspace_id")),
    )
    op.create_index(op.f("ix_scheduler_state_organization_id"), "scheduler_state", ["organization_id"], unique=False)
    op.create_index(op.f("ix_scheduler_state_workspace_id"), "scheduler_state", ["workspace_id"], unique=False)
    op.create_table(
        "working_memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_working_memories_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_working_memories_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_working_memories")),
        sa.UniqueConstraint(
            "workspace_id",
            "agent_id",
            "session_id",
            "key",
            name=op.f("uq_working_memories_workspace_id"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index("ix_working_memories_expires", "working_memories", ["expires_at"], unique=False)
    op.create_index(op.f("ix_working_memories_organization_id"), "working_memories", ["organization_id"], unique=False)
    op.create_index(op.f("ix_working_memories_workspace_id"), "working_memories", ["workspace_id"], unique=False)
    op.create_table(
        "conflicts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("candidate_memory_id", sa.UUID(), nullable=False),
        sa.Column("existing_memory_id", sa.UUID(), nullable=False),
        sa.Column("conflict_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "analysis_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "resolution_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('open', 'resolved')", name=op.f("ck_conflicts_status")),
        sa.ForeignKeyConstraint(
            ["candidate_memory_id"],
            ["memories.id"],
            name=op.f("fk_conflicts_candidate_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["existing_memory_id"],
            ["memories.id"],
            name=op.f("fk_conflicts_existing_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_conflicts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_conflicts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conflicts")),
        sa.UniqueConstraint("candidate_memory_id", "existing_memory_id", name=op.f("uq_conflicts_candidate_memory_id")),
    )
    op.create_index(op.f("ix_conflicts_organization_id"), "conflicts", ["organization_id"], unique=False)
    op.create_index(op.f("ix_conflicts_workspace_id"), "conflicts", ["workspace_id"], unique=False)
    op.create_table(
        "experiences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.String(length=200), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("observation", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_trust", sa.Float(), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('success', 'failure', 'partial', 'unknown')", name=op.f("ck_experiences_outcome")
        ),
        sa.CheckConstraint(
            "processing_status IN ('pending','processed','failed')",
            name=op.f("ck_experiences_processing_status"),
        ),
        sa.CheckConstraint("source IN ('agent', 'user', 'tool', 'external')", name=op.f("ck_experiences_source")),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
            name=op.f("fk_experiences_episode_id_episodes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_experiences_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_experiences_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiences")),
    )
    op.create_index(op.f("ix_experiences_organization_id"), "experiences", ["organization_id"], unique=False)
    op.create_index(op.f("ix_experiences_project_id"), "experiences", ["project_id"], unique=False)
    op.create_index(op.f("ix_experiences_workspace_id"), "experiences", ["workspace_id"], unique=False)
    op.create_index("ix_experiences_ws_created", "experiences", ["workspace_id", "created_at"], unique=False)
    op.create_table(
        "memory_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "relation IN ('supports','derived_from','contradicts')", name=op.f("ck_memory_evidence_relation")
        ),
        sa.CheckConstraint(
            "source_type IN ('event', 'episode', 'experience', 'user_statement', 'document', 'tool_result', 'memory', 'feedback')",
            name=op.f("ck_memory_evidence_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_evidence_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memory_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_evidence")),
        sa.UniqueConstraint(
            "memory_id", "source_type", "source_id", "relation", name=op.f("uq_memory_evidence_memory_id")
        ),
    )
    op.create_index(op.f("ix_memory_evidence_memory_id"), "memory_evidence", ["memory_id"], unique=False)
    op.create_index(op.f("ix_memory_evidence_organization_id"), "memory_evidence", ["organization_id"], unique=False)
    op.create_index("ix_memory_evidence_source", "memory_evidence", ["source_type", "source_id"], unique=False)
    op.create_table(
        "memory_feedback",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.String(length=200), nullable=True),
        sa.Column("retrieval_trace_id", sa.UUID(), nullable=True),
        sa.Column("value", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "value IN ('helpful', 'irrelevant', 'incorrect', 'outdated', 'harmful')",
            name=op.f("ck_memory_feedback_value"),
        ),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_feedback_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memory_feedback_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_memory_feedback_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_feedback")),
    )
    op.create_index(op.f("ix_memory_feedback_memory_id"), "memory_feedback", ["memory_id"], unique=False)
    op.create_index(op.f("ix_memory_feedback_organization_id"), "memory_feedback", ["organization_id"], unique=False)
    op.create_index(op.f("ix_memory_feedback_workspace_id"), "memory_feedback", ["workspace_id"], unique=False)
    op.create_table(
        "memory_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("source_memory_id", sa.UUID(), nullable=False),
        sa.Column("target_memory_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "relation IN ('supports', 'contradicts', 'supersedes', 'derived_from', 'related_to', 'generalizes', 'specializes')",
            name=op.f("ck_memory_relations_relation"),
        ),
        sa.CheckConstraint("source_memory_id <> target_memory_id", name=op.f("ck_memory_relations_no_self")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memory_relations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_relations_source_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_relations_target_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_relations")),
        sa.UniqueConstraint(
            "source_memory_id",
            "target_memory_id",
            "relation",
            name=op.f("uq_memory_relations_source_memory_id"),
        ),
    )
    op.create_index(op.f("ix_memory_relations_organization_id"), "memory_relations", ["organization_id"], unique=False)
    op.create_index(
        op.f("ix_memory_relations_source_memory_id"), "memory_relations", ["source_memory_id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_relations_target_memory_id"), "memory_relations", ["target_memory_id"], unique=False
    )
    op.create_table(
        "memory_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("change_reason", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_memory_versions_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memory_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_versions")),
        sa.UniqueConstraint("memory_id", "version", name=op.f("uq_memory_versions_memory_id")),
    )
    op.create_index(op.f("ix_memory_versions_memory_id"), "memory_versions", ["memory_id"], unique=False)
    op.create_index(op.f("ix_memory_versions_organization_id"), "memory_versions", ["organization_id"], unique=False)
    op.create_table(
        "retrieval_trace_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("memory_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"],
            ["memories.id"],
            name=op.f("fk_retrieval_trace_items_memory_id_memories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_retrieval_trace_items_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trace_id"],
            ["retrieval_traces.id"],
            name=op.f("fk_retrieval_trace_items_trace_id_retrieval_traces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retrieval_trace_items")),
        sa.UniqueConstraint("trace_id", "memory_id", name=op.f("uq_retrieval_trace_items_trace_id")),
    )
    op.create_index(op.f("ix_retrieval_trace_items_memory_id"), "retrieval_trace_items", ["memory_id"], unique=False)
    op.create_index(
        op.f("ix_retrieval_trace_items_organization_id"),
        "retrieval_trace_items",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_sessions_agent_id_agents"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sessions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_sessions_project_id_projects"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sessions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_organization_id"), "sessions", ["organization_id"], unique=False)
    op.create_index(op.f("ix_sessions_workspace_id"), "sessions", ["workspace_id"], unique=False)
    # ### end Alembic commands ###

    op.execute("CREATE INDEX ix_memories_embedding_hnsw ON memories USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX ix_episodes_embedding_hnsw ON episodes USING hnsw (embedding vector_cosine_ops)")
    # Events are immutable (L0): forbid UPDATE at the database level.
    op.execute(
        """
        CREATE FUNCTION mnemos_forbid_update() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'table % is append-only', TG_TABLE_NAME; END $$;
        """
    )
    op.execute(
        "CREATE TRIGGER events_immutable BEFORE UPDATE ON events FOR EACH ROW EXECUTE FUNCTION mnemos_forbid_update()"
    )
    op.execute(
        "CREATE TRIGGER memory_versions_immutable BEFORE UPDATE ON memory_versions "
        "FOR EACH ROW EXECUTE FUNCTION mnemos_forbid_update()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS memory_versions_immutable ON memory_versions")
    op.execute("DROP TRIGGER IF EXISTS events_immutable ON events")
    op.execute("DROP FUNCTION IF EXISTS mnemos_forbid_update()")
    op.execute("DROP INDEX IF EXISTS ix_episodes_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_memories_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_workspace_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_organization_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_retrieval_trace_items_organization_id"), table_name="retrieval_trace_items")
    op.drop_index(op.f("ix_retrieval_trace_items_memory_id"), table_name="retrieval_trace_items")
    op.drop_table("retrieval_trace_items")
    op.drop_index(op.f("ix_memory_versions_organization_id"), table_name="memory_versions")
    op.drop_index(op.f("ix_memory_versions_memory_id"), table_name="memory_versions")
    op.drop_table("memory_versions")
    op.drop_index(op.f("ix_memory_relations_target_memory_id"), table_name="memory_relations")
    op.drop_index(op.f("ix_memory_relations_source_memory_id"), table_name="memory_relations")
    op.drop_index(op.f("ix_memory_relations_organization_id"), table_name="memory_relations")
    op.drop_table("memory_relations")
    op.drop_index(op.f("ix_memory_feedback_workspace_id"), table_name="memory_feedback")
    op.drop_index(op.f("ix_memory_feedback_organization_id"), table_name="memory_feedback")
    op.drop_index(op.f("ix_memory_feedback_memory_id"), table_name="memory_feedback")
    op.drop_table("memory_feedback")
    op.drop_index("ix_memory_evidence_source", table_name="memory_evidence")
    op.drop_index(op.f("ix_memory_evidence_organization_id"), table_name="memory_evidence")
    op.drop_index(op.f("ix_memory_evidence_memory_id"), table_name="memory_evidence")
    op.drop_table("memory_evidence")
    op.drop_index("ix_experiences_ws_created", table_name="experiences")
    op.drop_index(op.f("ix_experiences_workspace_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_project_id"), table_name="experiences")
    op.drop_index(op.f("ix_experiences_organization_id"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(op.f("ix_conflicts_workspace_id"), table_name="conflicts")
    op.drop_index(op.f("ix_conflicts_organization_id"), table_name="conflicts")
    op.drop_table("conflicts")
    op.drop_index(op.f("ix_working_memories_workspace_id"), table_name="working_memories")
    op.drop_index(op.f("ix_working_memories_organization_id"), table_name="working_memories")
    op.drop_index("ix_working_memories_expires", table_name="working_memories")
    op.drop_table("working_memories")
    op.drop_index(op.f("ix_scheduler_state_workspace_id"), table_name="scheduler_state")
    op.drop_index(op.f("ix_scheduler_state_organization_id"), table_name="scheduler_state")
    op.drop_table("scheduler_state")
    op.drop_index("ix_retrieval_traces_ws_created", table_name="retrieval_traces")
    op.drop_index(op.f("ix_retrieval_traces_workspace_id"), table_name="retrieval_traces")
    op.drop_index(op.f("ix_retrieval_traces_organization_id"), table_name="retrieval_traces")
    op.drop_table("retrieval_traces")
    op.drop_index(op.f("ix_projects_workspace_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_memories_ws_status", table_name="memories")
    op.drop_index(op.f("ix_memories_workspace_id"), table_name="memories")
    op.drop_index("ix_memories_search_tsv", table_name="memories", postgresql_using="gin")
    op.drop_index(op.f("ix_memories_organization_id"), table_name="memories")
    op.drop_index("ix_memories_content_hash", table_name="memories")
    op.drop_index(
        "ix_memories_active_scope",
        table_name="memories",
        postgresql_where=sa.text("status IN ('active','validated')"),
    )
    op.drop_table("memories")
    op.drop_index("ix_events_ws_occurred", table_name="events")
    op.drop_index(op.f("ix_events_workspace_id"), table_name="events")
    op.drop_index(op.f("ix_events_session_id"), table_name="events")
    op.drop_index(op.f("ix_events_organization_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_eval_runs_workspace_id"), table_name="eval_runs")
    op.drop_index(op.f("ix_eval_runs_organization_id"), table_name="eval_runs")
    op.drop_table("eval_runs")
    op.drop_index(op.f("ix_episodes_workspace_id"), table_name="episodes")
    op.drop_index(op.f("ix_episodes_organization_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_index("uq_dream_jobs_window", table_name="dream_jobs", postgresql_where=sa.text("window_hash IS NOT NULL"))
    op.drop_index(op.f("ix_dream_jobs_workspace_id"), table_name="dream_jobs")
    op.drop_index(op.f("ix_dream_jobs_organization_id"), table_name="dream_jobs")
    op.drop_table("dream_jobs")
    op.drop_index(op.f("ix_agents_workspace_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_organization_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_workspaces_organization_id"), table_name="workspaces")
    op.drop_table("workspaces")
    op.drop_index(op.f("ix_idempotency_keys_organization_id"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_audit_logs_workspace_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_org_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_api_keys_organization_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("organizations")
    op.drop_index("ix_jobs_running_lease", table_name="jobs", postgresql_where=sa.text("status = 'running'"))
    op.drop_index("ix_jobs_ready", table_name="jobs", postgresql_where=sa.text("status IN ('queued','failed')"))
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
